server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # create - 재시작하면 테이블이 지우고 다시 만듦. update - 유지.
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect